services:
  db:
    restart: always
    image: "postgres:16"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - PORT=
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - ""

